#!/bin/bash

# radio - Bash shell script for listening radio basically

# Copyright 2020, Taeseong Ryu <formeu2s@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

# LIVE 언제, 어디서나 KBS 24시뉴스 https://www.youtube.com/watch?v=cUaptEjecPE
# YTN LIVE 대한민국 24시간 뉴스채널 https://www.youtube.com/watch?v=U_sYIKWhJvk
# live 연합뉴스TV https://www.youtube.com/watch?v=0GN8t2u3flc
# CNA 24/7 LIVE https://www.youtube.com/watch?v=XWq5kBlakcQ
# ANNnewsCH https://www.youtube.com/watch?v=coYw-eVU0Ks
# Taiwan Formosa live news HD https://www.youtube.com/watch?v=XxJKnDLYZz4
# Taiwan EBC 24h live news https://www.youtube.com/watch?v=RaIJ767Bj_M
# Watch NBC News NOW Live https://www.youtube.com/watch?v=6hRk_zPTN1c
# NBC2 Live Stream https://www.youtube.com/watch?v=tPeUHECNLKs
# Watch The Latest News Headlines and Live Events: ABC News Live https://www.youtube.com/watch?v=w_Ma8oQLmSM
# Al Jazeera English | Live https://www.youtube.com/watch?v=_dsWF2prkR8
# Watch Sky News live https://www.youtube.com/watch?v=9Auq9mYxFEE
# Euronews English Live https://www.youtube.com/watch?v=4MHhTZaGt2w
# FRANCE 24 English – LIVE – International Breaking News & Top stories - 24/7 stream https://www.youtube.com/watch?v=FUnJzFT2i84
# LIVE: Puthiya Thalaimurai Live News | Tamil News | Live Tamil News | Ayodhya Ram temple | Sushant https://www.youtube.com/watch?v=AyOCx_DHXJU
# OTV Live 24x7 | Latest News Updates | Coronavirus(COVID-19) News | Unlock 3.0 Updates | Odisha TV https://www.youtube.com/watch?v=Axu-FoqBIXY
# Sakshi TV LIVE | Today 'Telugu News' LIVE  https://www.youtube.com/watch?v=8McTsOqeueE
# Manorama News LIVE TV https://www.youtube.com/watch?v=jjH6v95z3Nw
# Watch SAMAA TV's News LIVE STREAM 24/7 | Full Pakistan coverage https://www.youtube.com/watch?v=vBjv7ZkRzig
# LIVE STREAMING KOMPAS TV 24/7 https://www.youtube.com/watch?v=gIB2egm7tL8
# NETTV LIVE 2020 https://www.youtube.com/watch?v=WZ83bBwWZQY
# Channels Television Live https://www.youtube.com/watch?v=MSQhwpYQbtQ
# TGRT Haber TV Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=5J8uR3mxq80
# Habertürk TV Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=deKH0pQ7-rg