#!/bin/bash

# radio - Bash shell script for listening radio

# Copyright 2020, Taeseong Ryu <formeu2s@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License at <http://www.gnu.org/licenses/> for
# more details.

# this script for my favorite music from various sources
# like radio, youtube, local storage
#
# Usage: radio [urlname] or radio option [arg ...]
#
# radio
#       - plays a shuffled radio, press 'q' to play the next.
#         this loops infinitely, press Ctrl-c repeatedly to exit.
#
# radio "regex"
#       - plays a searched item.
#         need quote for "or" regex searching like "wordA\|wordB".
#         don't need quote for "and" regex searching, only white-space needed.
#         You can use -v to invert match
#         you can select items like 3-5 7 11 15-20
#         ex) radio "sia\|live\|tv" cam "mango\|full"
#             radio sia -v lsd - include "sia" but not "lsd"
#
# Options:
#
# -a | --all
#       - displays all urls, choose a number.
#
# -g | --group {en|kr|jp|mv|lt|ln|lc|pl}
#       - plays a shuffled radio in a group, press 'q' to play the next.
#         this loops infinitely, press Ctrl-c repeatedly to exit.
#         ex) radio -g jp - play only the Japanese radio randomly
#
# -l | --local ["regex"]
#       - plays a shuffled local music.
#         this loops infinitely, press Ctrl-c repeatedly to exit.
#         ex) radio -l sia - play only local files with sia
#
# -t | --test
#       - tests all radios whether work or not.
#         If failed, it logs on the file named report.
#
# -e | --edit
#       - edit this script.
#
# -h | --help
#       - prints this help.



### TODO
#
# add more urls
# add youtube searching directly
# select narrowly and recursively
# load another source file



# set -u # avoid a undeclared variable

garg=("$@")
garg0="$0"
garg1="$1"
garg2="$2"
PROGNAME=${garg0##*/}
VERSION="0.1"
PS3="
# 1 3 5-7 8 or regex
# for all, press 00
choose : "
PLAYER="mpv"
LOCALVIDEODIR="/mnt/data/Videos/"
LOCALMUSICDIR="/mnt/data/Music/"
LOCALMUSICEXT=".*\.(mp3|flac)$"
RADIOSTARTLINE="### MY RADIO URLS"
RADIOENDLINE="### MY RADIO URLS END"
YOUTUBESTARTLINE="### MY YOUTUBE URLS"
YOUTUBEENDLINE="### MY YOUTUBE URLS END"
LOCALSTARTLINE="### MY LOCAL MUSIC"
LOCALENDLINE="### MY LOCAL MUSIC END"
TESTENDLINE="### TEST END"
SCRIPTDIR="${garg0%/*}"
REPORTPATH="$SCRIPTDIR/report"
REPORTFIRSTLINE="### ERROR REPORT"
TESTTIME=10 # sec
PERIODTIME=600
# basic regex: ‘\?’, ‘\+’, ‘\{’, ‘\|’, ‘\(’, and ‘\)’
SKIPPATTERN="^#\?$\|^##\+\|^#[^ ]\|^#  \+"
playlistnumber=1
E_IN_A_ROW=64 # error code for the same item in a row



search_linenumber() {
    local arg1="$1"
    local arg2="$2"
    x=0
    if [[ -f "$arg1" ]] ; then
        while read -r line ; do
            (( x++ ))
            [[ $line =~ $arg2 ]] && break # unquote for regex
        done < "$arg1"
    else
        while read -r line ; do
            (( x++ ))
            [[ $line =~ $arg2 ]] && break
        done <<< "$arg1"
    fi
    # test_print search_linenumber $x
    return 0
}

back_trace() {
    local maxlength format1
    for key in "${!FUNCNAME[@]}" ; do
        if (( "${#FUNCNAME[$key]}" > ${maxlength:-0} )) ; then
            maxlength="${#FUNCNAME[$key]}"
        fi
    done
    format1="\n%-${maxlength}s : %5s"
    printf "$format1" "LINENO"  "${LINENO}"
    for key in "${!BASH_LINENO[@]}" ; do
        printf "$format1" "${FUNCNAME[$key]}" "${BASH_LINENO[$key]}"
    done
    printf "\n"
}

test_print() {
    local arg1="$1"
    local arg2="$2"
    local linesnumber format1
    linesnumber=$(wc -l <<< "$arg2")
    if (( linesnumber == 1 )) ; then
        printf "\n"
        printf "\n${arg1} is ${arg2}"
        printf "\n"
    elif (( linesnumber > 1 && linesnumber < 10)) ; then
        printf "\n"
        printf "\n${arg1} is \n${arg2}"
        printf "\n"
    else
        printf "\n"
        printf "\n${arg1} is \n${arg2}"
        printf "\n${linesnumber} lines"
        printf "\n"
    fi
    # format1="\n%-${maxlength}s : %5s"
    # printf "$format1" "${FUNCNAME[test_print]}" "${BASH_LINENO[test_print]}"
    # printf "\n"
    # back_trace
    return 0
}

grep_print() {
    local arg1="$1"
    if [[ "$arg1" =~ https?:/ ]] ; then
        printf "\n"
        awk -F 'http' '{print $1}' <<< "$arg1" \
            | sed 's/^# / /' \
            | grep --color=auto .
        printf "\n"
    elif [[ "$arg1" =~ /$ ]] ; then
        printf "\n"
        sed 's/^# / /' <<< "$arg1" | grep --color=auto .
        printf "\n"
    elif [[ "$arg1" =~ /mnt/ ]] ; then
        printf "\n"
        awk -F '/mnt/' '{print $1}' <<< "$arg1" \
            | sed 's/^# / /' \
            | grep --color=auto .
        printf "\n"
    else
        printf "\n"
        grep --color=auto . <<< "$arg1"
        printf "\n"
    fi
    return 0
}

make_namelist() {
    # grep 'and' option
    local arg1="$1"
    local reverse
    for line in "${garg[@]}" ; do
        # test_print line "$line"
        if [[ -z $grepnames ]] ; then
            if [[ $line =~ ^-+[a-z]+ ]] ; then
                continue
            fi
            grepnames=$(grep -i "$line" <<< "$arg1")
        else
            test_print line "$line"
            if [[ $line == -v ]] ; then
                reverse="-v"
                continue
            fi
            grepnames=$(grep -i $reverse "$line" <<< "$grepnames")
            if [[ -n $reverse ]] ; then
                reverse=""
            fi
        fi
    done
    # test_print "make_namelist()'s grepnames" "$grepnames"
    return 0
}

remove_parts() {
    local arg1="$1"
    if [[ "$arg1" =~  https?:// ]] ; then
        grepnames=$(awk -F 'http' '{print $1}' <<< "$arg1")
    elif [[ "$arg1" =~ ^/mnt/ ]] ; then
        grepnames=$(sed 's/.*Music\///g'<<< "$arg1" )
    elif [[ "$arg1" =~  /mnt/ ]] ; then
        grepnames=$(awk -F '/mnt/' '{print $1}' <<< "$arg1")
    fi
    return 0
}

print_shufflelist() {
    local arg1="$1"
    local print_grepnames
    # test_print arg1 "$arg1"
    if [[ "$arg1" =~  https?:// ]] ; then
        print_grepnames=$(awk -F 'http' '{print $1}' <<< "$arg1")
    elif [[ "$arg1" =~ ^/mnt/ ]] ; then
        print_grepnames=$(sed 's/.*Music\///g'<<< "$arg1" )
    elif [[ "$arg1" =~  /mnt/ ]] ; then
        print_grepnames=$(awk -F '/mnt/' '{print $1}' <<< "$arg1")
    else
        print_grepnames="$arg1"
    fi
    test_print shufflelist "${shufflelist:-"$arg1"}"
    return 0
}

shuffle_list() {
    # all items must be selected only once for one-cycle
    local arg1="$1"
    local firstshuffle
    if [[ -z "$shufflelist" ]] ; then
        print_shufflelist "$arg1"
        firstshuffle=$(shuf -n 1 <<< "$arg1")
        # avoid selecting the same item in a row
        if [[ "$firstshuffle" == "$lastshuffle" ]] ; then
            printf "\n continue \n"
            return $E_IN_A_ROW
        else
            shufflelist=$(grep -vF "$firstshuffle" <<< "$arg1") # needed -F
            shuffleradio="$firstshuffle"
        fi
    else
        print_shufflelist "$shufflelist"
        lastshuffle=$(shuf -n 1 <<< "$shufflelist")
        shufflelist=$(grep -vF "$lastshuffle" <<< "$shufflelist")
        shuffleradio="$lastshuffle"
    fi
    # eval "$2=\$arg2" # bash special form for returning a string
    return 0
}

play() {
    local arg1="$1"
    local partline namepart optionpart lastbgpid
    (( count++ ))
    # test_print count "$count"
    if [[ "$arg1" =~  https?:// ]] ; then
        partline=${arg1/*http/http}
        # partline=$(awk -F 'http' '{print FS$2}' <<< "$arg1")
    elif [[ "$arg1" =~ /$ ]] ; then
        partline="$LOCALMUSICDIR"$(sed 's/^# //' <<< "$arg1")
    elif [[ "$arg1" =~ ^/mnt/ ]] ; then
        partline="$arg1"
    elif [[ "$arg1" =~  /mnt/ ]] ; then
        partline=${arg1/*mnt/mnt}
        # partline=$(awk -F '/mnt/' '{print FS$2}' <<< "$arg1")
    else
        printf "\n"
        printf "\n play()"
        printf "\n Sorry, something is wrong!"
        printf "\n"
        exit 1
    fi
    if [[ "$partline" =~  --[a-z]+ ]] ; then
        # test_print partline "$partline"
        namepart=${partline%% --*} # need space for trailing
        # test_print namepart "$namepart"
        optionpart=${partline#"$namepart"}
        $PLAYER "$namepart" $optionpart & # don't quote rest options
    else
        $PLAYER "$partline" &
    fi
    lastbgpid=$!
    wait $lastbgpid
    # sleep 1
    count=0
    partlinelist=""
    return 0
}

play_radio() {
    while true ; do
        radiolist=$(grep -v "$SKIPPATTERN" <<< "$radiolist")
        shuffle_list "$radiolist"
        (( $? == $E_IN_A_ROW )) && continue
        grep_print "$shuffleradio"
        play "$shuffleradio"
    done
    return 0
}

show_all(){
    radio .
    return 0
}

play_group() {
    x=0
    while read -r line ; do
        (( x++ ))
        case "$garg2" in
            en)
                [[ $line =~ ^"## English Radio" ]] && break
                ;;
            kr)
                [[ $line =~ ^"## Korean Radio" ]] && break
                ;;
            jp)
                [[ $line =~ ^"## Japanese Radio" ]] && break
                ;;
            mv)
                [[ $line =~ ^"## Music Video" ]] && break
                ;;
            lt)
                [[ $line =~ ^"## Live TV" ]] && break
                ;;
            ln)
                [[ $line =~ ^"## Live News" ]] && break
                ;;
            lc)
                [[ $line =~ ^"## Live Camera" ]] && break
                ;;
            pl)
                [[ $line =~ ^"## Play List" ]] && break
                ;;
            *)
                printf "\n Sorry, there is no \"$2\" group."
                printf "\n"
                printf "\n Usage: radio -g {en|kr|jp|mv|lt|ln|lc|pl}"
                printf "\n"
                printf "\n en - English Radio"
                printf "\n kr - Korean Radio"
                printf "\n jp - Japanese Radio"
                printf "\n mv - Music Video"
                printf "\n lt - Live TV"
                printf "\n ln - Live News"
                printf "\n lc - Live Camera"
                printf "\n pl - Play List"
                printf "\n"
                exit 2
        esac
    done <<< "$urllist"
    grouplist=$(tail -n +"$(( x + 2 ))" <<< "$urllist")
    search_linenumber "$grouplist" "^##+"
    grouplist=$(head -n "$(( x - 2 ))" <<< "$grouplist")
    while true ; do
        grouplist=$(grep -v "$SKIPPATTERN" <<< "$grouplist")
        shuffle_list "$grouplist"
        (( $? == $E_IN_A_ROW )) && continue
        grep_print "$shuffleradio"
        play "$shuffleradio"
        sleep 1
    done
    return 0
}

select_all() {
    printf "\n"
    printf "\n You chose all items."
    printf "\n They'll be played randomly and infinitely."
    printf "\n To exit, press Ctrl-c repeatedly"
    printf "\n"
    while true ; do
        shuffle_list "$grepnames"
        (( $? == $E_IN_A_ROW )) && continue
        grep_print "$shuffleradio"
        grepline=$(grep -iF "$shuffleradio" <<< "$arg2")
        play "$grepline"
        # sleep 1
    done
    return 0
}

select_sed() {
    printf "\n"
    printf "\n You selected multiple items with number."
    printf "\n they'll be played randomly and infinitely."
    printf "\n To exit, press Ctrl-c repeatedly"
    printf "\n"
    # like 3-5 7 11 15-20 --> 3,5p;11;15,20p for sed
    # ex) with space
    #    5     -5  7  8-   9  --> 5p;7p;8,9p
    REPLY=$(sed 's/^ \+//g' <<< "$REPLY" \
                | sed 's/ \+$//g' \
                | sed 's/ \+/ /g' \
                | sed 's/ -/-/g' \
                | sed 's/- /-/g' \
                | sed 's/ /p;/g' \
                | sed 's/-/,/g' \
                | sed 's/$/p/')
    # test_print REPLY "$REPLY"
    grepnames=$(sed -n "$REPLY" <<< "$grepnames")
    while true ; do
        shuffle_list "$grepnames"
        (( $? == $E_IN_A_ROW )) && continue
        grep_print "$shuffleradio"
        grepline=$(grep -iF "$shuffleradio" <<< "$arg2")
        play "$grepline"
        # sleep 1
    done
    return 0
}

select_regex() {
    printf "\n"
    printf "\n You selected items with no number."
    printf "\n they'll be played randomly and infinitely."
    printf "\n To exit, press Ctrl-c repeatedly"
    printf "\n"
    while true ; do
        grepnames=$(grep -i "$REPLY" <<< "$grepnames")
        shuffle_list "$grepnames"
        (( $? == $E_IN_A_ROW )) && continue
        grep_print "$shuffleradio"
        grepline=$(grep -iF "$shuffleradio" <<< "$arg2")
        play "$grepline"
        # sleep 1
    done
    return 0
}

select_list() {
    local arg1="$1"
    local arg2="$2"
    local arg3="$3"
    if (( $arg1 == 1 )) ; then
        grep_print "$arg3"
        # grep '-F' for only string like "[live] tv"
        grepline=$(grep -iF "$arg3" <<< "$arg2")
        play "$grepline"
    elif (( $arg1 > 1 )) ; then
        remove_parts "$arg3"
        # test_print grepnames "$grepnames"
        readarray -t arr_names <<< "$grepnames"
        select url in "${arr_names[@]}" ; do
            if [[ $REPLY =~ ^00$ ]] ; then
                select_all
                exit 0
            elif [[ $REPLY =~ [0-9]+[-\ ]+[0-9]+ ]] ; then
                select_sed
                exit 0
            elif [[ $REPLY =~ [^0-9] ]] ; then
                select_regex
                exit 0
            fi
            selectedurl="$url"
            break
        done
        grep_print "$selectedurl"
        grepline=$(grep -iF "$selectedurl" <<< "$arg2")
        play "$grepline"
        exit 0
    else
        printf "\n"
        printf "\n select_list()"
        printf "\n Sorry, the \"$1\" does not match."
        printf "\n"
        exit 1
    fi
}

play_local() {
    search_linenumber "$urllist" "^$LOCALSTARTLINE"
    locallist=$(tail -n +"$(( x + 2 ))" <<< "$urllist")
    search_linenumber "$locallist" "^##+"
    locallist=$(head -n "$(( x - 2 ))" <<< "$locallist")
    if [[ -z "$garg2" ]] ; then
        while true ; do
            locallist=$(grep -v "$SKIPPATTERN" <<< "$locallist")
            shuffle_list "$locallist"
            (( $? == $E_IN_A_ROW )) && continue
            grep_print "$shuffleradio"
            play "$shuffleradio"
            # sleep 1
        done
    else
        shopt -s globstar
        for file in "$LOCALMUSICDIR"**/* ; do
            if [[ $file =~ $LOCALMUSICEXT ]] ; then
                localoneline+=("$file")
            fi
        done
        locallist=$(printf '%s\n' "${localoneline[@]}")
        # test_print locallist "$locallist"
        make_namelist "$locallist"
        grepcount=$(grep -ic .  <<< "$grepnames")
        # test_print greplocalcount "$greplocalcount"
        select_list "$grepcount" "$locallist" "$grepnames"
    fi
    return 0
}

test_items() {
    search_linenumber "$urllist" "^$TESTENDLINE"
    testlist=$(head -n +$x <<< "$urllist")
    cat > "$REPORTPATH" <<< "$REPORTFIRSTLINE"
    while read -r line ; do
        (( $(grep -c "$SKIPPATTERN" <<< "$line") )) &&continue
        grep_print "$line"
        $PLAYER $(awk -F 'http' '{print FS$2}' <<< "$line") &
        lastbgpid=$!
        sleep $TESTTIME
        if (( $(ps aux | grep -c $lastbgpid) == 1 )) ; then
            echo "$line" >> "$REPORTPATH"
        else
            kill $lastbgpid
        fi
        sleep 1
    done <<< "$testlist"
    printf "\n"
    cat "$REPORTPATH"
    printf "\n"
    return 0
}

edit_this() {
    $EDITOR $HOME/git/radio/radio
    return 0
}

help_usage() {
    search_linenumber "$garg0" "^# Usage"
    helplist=$(tail -n +$(( x - 3 )) "$garg0")
    search_linenumber "$helplist" "^$"
    helplist=$(head -n $x <<< "$helplist")
    printf "\n"
    sed 's/#\+//' <<< "$helplist"
    printf "\n"
    return 0
}



search_linenumber "$garg0" "^$RADIOSTARTLINE"
urllist=$(tail -n +"$(( x + 4 ))" "$garg0")
# test_print urllist "$urllist"
search_linenumber "$urllist" "^$RADIOENDLINE"
radiolist=$(head -n +"$(( x - 2 ))" <<< "$urllist")
# test_print radiolist "$radiolist"
urlname="${urllist/http*/}"
# urlname=$(awk -F 'http' '{print $1}' <<< "$urllist")
# test_print urlname "$urlname"
radioname="${radiolist/http*/}"
# radioname=$(awk -F 'http' '{print $1}' <<< "$radiolist")

# case use * ? [...] | as matching pattern
# case don't use regex and variables generally
# if you need those, use [[ =~ ]]
case "$garg1" in
    "")
        play_radio && exit 0
        ;;
    -a|--all)
        show_all && exit 0
        ;;
    -g|--group)
        play_group && exit 0
        ;;
    -l|--local)
        play_local && exit 0
        ;;
    -t|--test)
        test_items && exit 0
        ;;
    -e|--edit)
        edit_this && exit 0
        ;;
    -h|--help)
        help_usage && exit 0
        ;;
    # -x|--xxx) # not yet
    #     xxx_private && exit 0
    #   ;;
    # -y|--youtube) # not yet
    #   search_youtube && exit 0
    #   ;;
    *)
        make_namelist "$urllist"
        ;;
esac

grepnames=$(grep -v "$SKIPPATTERN" <<< "$grepnames" | sed 's/^# //')
# test_print grepnames "$grepnames"
grepcount=$(grep -ic .  <<< "$grepnames")
# test_print grepcount "$grepcount"
select_list "$grepcount" "$urllist" "$grepnames"



### MY RADIO URLS - from a latte applet in KDE.
#
# write a symptom without any space after # for error log
#
## English Radio
#
# BBC Radio London 94.9 FM http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrldn_mf_p
# NPR 24h Program Stream https://npr-ice.streamguys1.com/live.mp3
# CNN HLN http://tunein.streamguys1.com/cnnhln
# Fox News Radio https://streaming-ent.shoutcast.com/foxnews
# KWSU 1250 Northwest Public Radio NPR News - Pullman, WA http://streams.nwpr.org:8000/NWPRNEWS
# WNPR 90.5 Connecticut Public Radio - Meriden, CT http://16113.live.streamtheworld.com/WNPRFM_SC
# 90.5 WESA Pittsburgh's NPR New Station https://17273.live.streamtheworld.com:443/WESAFM.mp3
#
## Korean Radio
#
# SBS 러브 FM-SBS 라디오 http://slive.ytn.co.kr:1935/live/fmlive_0624_1.sdp/playlist.m3u8
# gukak http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8
# FM 95.1 TBS fm http://58.234.158.60:1935/fmlive/myStream/playlist.m3u8
#
## Japanese Radio
#
# KBS World Japanese Radio http://101.79.244.199:1935/cocotv/_definst_/CH00007/playlist.m3u8
# Kishiwada Radio http://61.89.201.27:8000/radikishi.mp3
# Kyoto Living FM (京都リビング FM/きょうと りびんぐ FM) http://musicbird.leanstream.co/JCB104-MP3
# FmHaro!76.1（エフエムハロー!） http://musicbird.leanstream.co/JCB034-MP3
# FM Fujiyama (FMふじやま, JOZZ3CA-FM, 77.6 MHz, Fujikawaguchiko, Yamanashi) http://musicbird.leanstream.co/JCB026-MP3
# Shuunan FM (しゅうなんFM, JOZZ8AJ-FM, 78.4 MHz, Shūnan, Yamaguchi) http://musicbird.leanstream.co/JCB085-MP3
# Air Tesshi (Airてっし, JOZZ1AU-FM, 78.8 MHz, Nayoro, Hokkaido) http://musicbird.leanstream.co/JCB003-MP3
# Umeda FM Be Happy! (ウメダFM Be Happy! 789/エフエムキタ, JOZZ7AK-FM, 78.9MHz, Kita-ku, Osaka) http://musicbird.leanstream.co/JCB068-MP3
# Happy FM Itami (ハッピーエフエムいたみ, JOZZ7AJ-FM, 79.4 MHz, Itami, Hyōgo) http://musicbird.leanstream.co/JCB070-MP3
# FM Yame (FM八女, JOZZ0BY-FM, 80.1 MHz, Yame, Fukuoka) http://musicbird.leanstream.co/JCB086-MP3
# FM Hanako (JOZZ7AA-FM, 82.4 MHz, Moriguchi City, Osaka) http://musicbird.leanstream.co/JCB069-MP3
# Kamakura FM 82.8 (かまくらFM, JOZZ3AF-FM, 82.8 MHz, Kamakura, Kanagawa) http://musicbird.leanstream.co/JCB016-MP3?args=tunein_02
# Ichikawa Urara FM (市川うららFM. JOZZ3AY-FM, 83.0 MHz, Ichikawa, Chiba) http://musicbird.leanstream.co/JCB020-MP3
# Humming FM Takarazuka (ハミングFM宝塚, JOZZ7AT-FM, 83.5 MHz, Takarazuka, Hyōgo) http://musicbird.leanstream.co/JCB071-MP3
# 84.3 FM Edogawa (FMえどがわ, JOZZ3AS-FM, Edogawa City, Tokyo) http://musicbird.leanstream.co/JCB032-MP3
# Shonan Magic Wave (湘南マジックウェィブ, JOZZ3CI-FM, 85.6 MHz, Ōiso, Kanagawa) http://musicbird.leanstream.co/JCB018-MP3
# FM Hana (FMはな, JOZZ1AZ-FM, 87.0 MHz, Nakashibetsu, Hokkaido) http://musicbird.leanstream.co/JCB001-MP3
# Banana FM (バナナエフエム, JOZZ7BE-FM, 87.7 MHz, Wakayama City) http://musicbird.leanstream.co/JCB075-MP3
#
### MY RADIO URLS END

### MY YOUTUBE URLS - need a youtube-dl to play a url.
#
## Music Video
#
# Дария «Нуки» Ставрович «Zombie» - Слепые прослушивания – Голос – Сезон 5 https://www.youtube.com/watch?v=pLN-EnS_QLA
# Дария Ставрович «Круги на воде» - Нокауты - Голос - Сезон 5 https://www.youtube.com/watch?v=AW3EJiRD0ho
# Дария Ставрович «Chandelier» - Полуфинал - Голос - Сезон 5 https://www.youtube.com/watch?v=ltV1yoeIoPM
# Sting - Shape of My Heart (Leon) https://www.youtube.com/watch?v=QK-Z1K67uaA
# What's up - EXCELENTE COVER!!! https://www.youtube.com/watch?v=1NNE0b55AoM
# nakashima mika - 僕が死のうと思ったのは (내가 죽으려고 마음먹었던 것은) https://www.youtube.com/watch?v=C6st9z_iaao
# nakashima mika - 中島美嘉『雪の華』 Music Video https://www.youtube.com/watch?v=oIoaIlPpIcA
# Amazarash(아마자라시 - 한글자막)  - 내가 죽으려고 생각한 것은【acoustic live ver】 https://www.youtube.com/watch?v=6SNscvxLP4E
# Sia - Big Girls Cry (Official Video) https://www.youtube.com/watch?v=4NhKWZpkw1Q
# Sia - The Greatest https://www.youtube.com/watch?v=GKSRyLdjsPA
# Sia - Together (from the motion picture Music) https://www.youtube.com/watch?v=vnfGni4_RlI
# Sia - Alive https://www.youtube.com/watch?v=t2NgsJrrAyM
# Sia - Unstoppable https://www.youtube.com/watch?v=H3evCDEXp4I
# Sia - Chandelier (Official Music Video) https://www.youtube.com/watch?v=2vjPBrBU-TM
# Sia - Elastic Heart feat. Shia LaBeouf & Maddie Ziegler (Official Video) https://www.youtube.com/watch?v=KWZGAExj-es
# LSD - Thunderclouds (Official Video) ft. Labrinth, Sia, Diplo https://www.youtube.com/watch?v=mILth-K6KvM
# LSD - No New Friends (Official Video) ft. Labrinth, Sia, Diplo https://www.youtube.com/watch?v=kkUIdK9eaIk
# LSD - Audio (Official Video) ft. Sia, Diplo, Labrinth https://www.youtube.com/watch?v=tjA7nAHOAww
# Queen - Love of My Life https://www.youtube.com/watch?v=v3xwCkhmies
# Queen - Love Of My Life (Live, 1979) https://www.youtube.com/watch?v=Idj__EDPCKk
# Queen - Somebody To Love - HD Live - 1981 Montreal https://www.youtube.com/watch?v=aA2IRoPFIn0
# Queen - Bohemian Rhapsody (Live at Rock Montreal, 1981) [HD] https://www.youtube.com/watch?v=N0dbGGvsjf8
# radiohead - Creep https://www.youtube.com/watch?v=XFkzRNyygfk
# Radiohead - Creep (Best Live Performance) https://www.youtube.com/watch?v=k3_RU30tEIE
# The Cranberries - Zombie 1999 Live Video https://www.youtube.com/watch?v=8MuhFxaT7zo
# 도시의 그림자 - 이 어둠의 이 슬픔 (1986) https://www.youtube.com/watch?v=BLPQySIh2Jk --start=00:12 --end=04:16 --volume=180
# 도시의 그림자(Shadow of City) - 이 어둠의 이 슬픔 (1986) https://www.youtube.com/watch?v=LW14PKtNvws --start=#3 --end=#4
# 노래얼_김옥희_이 어둠의 이 슬픔_고대 85학번 입학 30주년 기념 모교방문 축제 https://www.youtube.com/watch?v=cmNekU_svwY&list=RDcmNekU_svwY
# 강지민 - 이 어둠의 이 슬픔 (도시의 그림자) https://www.youtube.com/watch?v=lg6IKzPdoes --volume=70
# 심수봉 - 백만송이 장미 (1997년 6월 1일 이소라의 프로포즈) https://www.youtube.com/watch?v=z3Lkc8fEsww
# 떼창 할 수 밖에 없는 심수봉 - 남자는 배 여자는 항구♬ [유희열의 스케치북/You Heeyeol's Sketchbook] 20191220 https://www.youtube.com/watch?v=uRU58V_59jk
# 블랙홀(Black Hole) - 깊은 밤의 서정곡 https://www.youtube.com/watch?v=946hIajM-Hc

#--- local music video file ---#
# Frozen2 - Into the Unknown /mnt/data/Videos/Frozen 2 (2019)  [1080p x265 10bit FS93 Joy].mkv --start=#5 --end=20:06
# Frozen2 - Show Yourself /mnt/data/Videos/Frozen 2 (2019)  [1080p x265 10bit FS93 Joy].mkv --start=#15 --end=1:07:07
# Frozen2 - The Next Right Thing /mnt/data/Videos/Frozen 2 (2019)  [1080p x265 10bit FS93 Joy].mkv --start=#17 --end=1:17:24
# Frozen2 - Some things never change /mnt/data/Videos/Frozen 2 (2019)  [1080p x265 10bit FS93 Joy].mkv --start=09:13 --end=12:38
# Moana - how far I'll go /mnt/data/Videos/Moana (2016) 1080p 5.1 - 2.0 x264 Phun Psyz.mp4 --start=#4 --end=18:45
# Moana - I am Moana /mnt/data/Videos/Moana (2016) 1080p 5.1 x264 Phun Psyz.mp4 --start=1:20:54 --end=1:22:25
# Moana - Where you are /mnt/data/Videos/Moana (2016) 1080p 5.1 .0 x264 Phun Psyz.mp4 --start=07:45 --end=10:10
# Moana - You're welcome /mnt/data/Videos/Moana (2016) 1080p 5.1 2.0 x264 Phun Psyz.mp4 --start=38:20 --end=41:04
# Moana - shine /mnt/data/Videos/Moana (2016) 1080p 5.1 2.0 x264 Phun Psyz.mp4 --start=1:01:28 --end=1:04:42
# Moana - Tulou Tagaoa /mnt/data/Videos/Moana (2016) 1080p 5.1 2.0 x264 Phun Psyz.mp4 --start=23:50 --end=26:00
# Ghost in the shell 1995 - Original Soundtrack /mnt/data/Videos/Ghost.in.the.Shell.1995.JAPANESE.1080p.US.BluRay.H264.AAC-VXT.mp4 --start=03:56 --end=08:20
# Les.Miserables 2012 - Look down /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=55 --end=5:26
# Les.Miserables 2012 - I Dreamed A Dream /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=27:17 --end=31:51
# Les.Miserables 2012 - The Confrontation /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=43:20 --end=45:10
# Les.Miserables 2012 - Paris / Look Down /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=1:06:42 --end=1:09:36
# Les.Miserables 2012 - On My Own / Look Down /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=1:28:52 --end=1:32:00
# Les.Miserables 2012 - Do You Hear The People Sing? /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=1:35:35 --end=1:37:44
# Les.Miserables 2012 - Epilogue /mnt/data/Videos/Les.Miserables.2012.1080p.BluRay.x265-RARBG.mp4 --start=2:27:55 --end=2:29:40
#
## Live TV
#
# 正在直播：CCTV中文国际 https://www.youtube.com/watch?v=vCDDYb_M2B4
# franceinfo - DIRECT TV - actualité france et monde, interviews, documentaires et analyses https://www.youtube.c
# Tele1 TV | Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=TDy-nmXZNQM
# Adom TV Live https://www.youtube.com/watch?v=LIb1ADo0pGs
#
## Live News
#
# LIVE 언제, 어디서나 KBS 24시뉴스 https://www.youtube.com/watch?v=cUaptEjecPE
# YTN LIVE 대한민국 24시간 뉴스채널 https://www.youtube.com/watch?v=U_sYIKWhJvk
# live 연합뉴스TV https://www.youtube.com/watch?v=0GN8t2u3flc
# CNA 24/7 LIVE https://www.youtube.com/watch?v=XWq5kBlakcQ
# ANNnewsCH https://www.youtube.com/watch?v=coYw-eVU0Ks
# Taiwan Formosa live news HD https://www.youtube.com/watch?v=XxJKnDLYZz4
# Taiwan EBC 24h live news https://www.youtube.com/watch?v=RaIJ767Bj_M
# Watch NBC News NOW Live https://www.youtube.com/watch?v=6hRk_zPTN1c
# NBC2 Live Stream https://www.youtube.com/watch?v=tPeUHECNLKs
# Watch The Latest News Headlines and Live Events: ABC News Live https://www.youtube.com/watch?v=w_Ma8oQLmSM
# Al Jazeera English | Live https://www.youtube.com/watch?v=_dsWF2prkR8
# Watch Sky News live https://www.youtube.com/watch?v=9Auq9mYxFEE
# Euronews English Live https://www.youtube.com/watch?v=4MHhTZaGt2w
# FRANCE 24 English – LIVE – International Breaking News & Top stories - 24/7 stream https://www.youtube.com/watch?v=FUnJzFT2i84
# LIVE: Puthiya Thalaimurai Live News | Tamil News | Live Tamil News | Ayodhya Ram temple | Sushant https://www.youtube.com/watch?v=AyOCx_DHXJU
# OTV Live 24x7 | Latest News Updates | Coronavirus(COVID-19) News | Unlock 3.0 Updates | Odisha TV https://www.youtube.com/watch?v=Axu-FoqBIXY
# Sakshi TV LIVE | Today 'Telugu News' LIVE  https://www.youtube.com/watch?v=8McTsOqeueE
# Manorama News LIVE TV https://www.youtube.com/watch?v=jjH6v95z3Nw
# Watch SAMAA TV's News LIVE STREAM 24/7 | Full Pakistan coverage https://www.youtube.com/watch?v=vBjv7ZkRzig
# LIVE STREAMING KOMPAS TV 24/7 https://www.youtube.com/watch?v=gIB2egm7tL8
# NETTV LIVE 2020 https://www.youtube.com/watch?v=WZ83bBwWZQY
# Channels Television Live https://www.youtube.com/watch?v=MSQhwpYQbtQ
# TGRT Haber TV Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=5J8uR3mxq80
# Habertürk TV Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=deKH0pQ7-rg
#
## Live Camera - often change url address for restart
#
# 남산서울타워 파노라마 LIVE https://www.youtube.com/watch?v=uVTcfjw8sBw
# 鍛冶町通りライブカメラ［ザザシティ浜松］PTZ（パンチルトズーム）https://www.youtube.com/watch?v=PvoIqPjZFyA&feature=emb_logo
# Shibuya Scramble Crossing Live Camera https://www.youtube.com/watch?v=jEhIe2SDKso
# 【LIVE CAMERA】渋谷スクランブル交差点 ライブ映像 https://www.youtube.com/watch?v=I6YANW67hQ0
# 【LIVE】Tokyo Shinjuku Live Camera 新宿 大ガード交差点【2020】https://www.youtube.com/watch?v=RQA5RcIZlAM
# Downtown Telluride Live Camera https://www.youtube.com/watch?v=Y_TLxje5Qw4
# 秋葉原ライブカメラ Akihabara live camera YouTube Live version https://www.youtube.com/watch?v=mpFAKw68Je0
# KABUKICHO TOKYO Live Stream https://www.youtube.com/watch?v=kUeDK-f2IMk
# LIVE 道後温泉本館！！正面カメラ https://www.youtube.com/watch?v=vM7_-e0gdsc
# 【ライブ配信】丸沼高原　標高1500ｍ https://www.youtube.com/watch?v=m-U577NAs_U
# WATCH NASA: Earth Viewing cameras - Earth From Space ISS feed https://www.youtube.com/watch?v=DDU-rZs-Ic4
# EarthCam Live: Times Square in 4K https://www.youtube.com/watch?v=mRe-514tGMg
# Times Square: 1560 Broadway View Live https://www.youtube.com/watch?v=4qyZLflp-sI
# Times Square: Express View Live https://www.youtube.com/watch?v=uw0lpuMSe9E&feature=emb_logo
# Las Vegas: AE View Live https://www.youtube.com/watch?v=1ZNCtDLUKHw
# Avalanche Bay Indoor Waterpark, Boyne Mountain https://www.youtube.com/watch?v=mm_fnIJ1c6Q&feature=emb_logo
# Jackson Hole Wyoming USA Town Square Live Cam - SeeJH.com https://www.youtube.com/watch?v=1EiC9bvVGnk
# White Mountains TV Live Cam: North Conway Village https://www.youtube.com/watch?v=eT7Z70L5SPo
# Webcam Lanzarote - Live Stream from the Beachbar in Costa Teguise https://www.youtube.com/watch?v=NHkrWF5HMSE
# Live Stream — Public Square, Watertown NY — Jake Johnson Properties https://www.youtube.com/watch?v=qP1y7Tdab7Y&feature=emb_logo
# Tropical Murphys 1 Live Stream From Chaweng, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=0Ns1sNoUSaY
# Tropical Murphys 2 Live Stream From Chaweng, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=wXsYOpVP-kQ
# LIVE · Thailand / Koh Phangan / Haad Rin · Full Moon Party beach (AI Camera looking for people) https://www.youtube.com/watch?v=-Fen7JP8oHI&feature=emb_logo
# LIVE · Thailand / Koh Phangan · Thong Sala center (Mandolino Pizzeria) https://www.youtube.com/watch?v=1nnt_Beuo88&feature=emb_logo
# Hush Bar Cam, Soi Green Mango, Chaweng, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=wqvStiZyVBI
# Crystal Bay Yacht Club Live Stream From Lamai, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=aJdwAUUbFL8
# Crystal Bay Live Stream From Lamai, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=AK9TkxHCbHU
# LIVE · Thailand / Koh Phangan / Haad Rin · Full Moon Party beach (Seaview Sunrise Resort) https://www.youtube.com/watch?v=9WbCh2AE_NU
# Banff, AB Canada Live Cam https://www.youtube.com/watch?v=Tpchwvyv6yU
# Grancanaria.live | Playa del Inglés - Yumbo Center - LIVE ultraHD 4K PTZ https://www.youtube.com/watch?v=cvYNX6OONW4&feature=emb_logo
# WebCam.NL | www.sportsatsea.nl - live HD PTZ camera. https://www.youtube.com/watch?v=5rkyZrQv674&feature=emb_logo
# Beach Bar live HD Webcam in Cruz Bay https://www.youtube.com/watch?v=GrZ8LL8yAqs&feature=emb_logo
# Live da Club Camping Jesolo International https://www.youtube.com/watch?v=SDIPtTeTUdA
# Live Da Jesolo Spiagge - Oro Beach https://www.youtube.com/watch?v=zE_yzuxFiMo
# Lanzarote Webcam LIVE HD Streaming from Puerto del Carmen Beach (Lanzarote,Canary Islands,Spain) https://www.youtube.com/watch?v=mpd2CHIgJ9A
# Alanya Turkey, Alanya Türkei, Аланья Турция Palmiye Beach Hotel Live Camera https://www.youtube.com/watch?v=hYAaoI2E1Pw
# The central beach of Lignano Sabbiadoro (Italy) - Spiaggia LIVE streaming HD Webcam https://www.youtube.com/watch?v=jB_ix1xoj1c
# Historical city center "Piazza Fontana" of Lignano Sabbiadoro (Italy) - LIVE streaming HD Webcam https://www.youtube.com/watch?v=3J_-o4sB2RU
# Webcam Bari Sardo - Sardegna https://www.youtube.com/watch?v=IbgPG5L-uoI
# LIVE Deerfield Beach - Beach Camera https://www.youtube.com/watch?v=-HAi_5IIAYg&feature=emb_logo
# Underwater Camera in Deerfield Beach, Florida https://www.youtube.com/watch?v=GAv4VCC41oU
# Dania Beach Pier and Beach Cam https://www.youtube.com/watch?v=bEoNVd3spEM&feature=emb_logo
# Sportovní areál - Maškova zahrada, Turnov https://www.youtube.com/watch?v=meUtwDS6fVk&feature=emb_logo
# HC Lomnice nad Popelkou https://www.youtube.com/watch?v=7AGre-USTMc
# Lomnice nad Popelkou - Koupaliště https://www.youtube.com/watch?v=MAIRHYclfyM
# Lomnice nad Popelkou - Koupaliště (kamera 2) https://www.youtube.com/watch?v=sDKNrdqMcqE
# Lomnice nad Popelkou - Husovo náměstí https://www.youtube.com/watch?v=IsJWaa_KMVc
# Lomnice nad Popelkou - TENIS - pohled ke klubovně https://www.youtube.com/watch?v=vPWxzpc0Iek
# Lomnice nad Popelkou - tour https://www.youtube.com/watch?v=qAWlaKoSqa4
# TJ Sokol Nová Ves nad Popelkou, z.s. , fotbalové hřiště https://www.youtube.com/watch?v=Bg2JXM5KcII
# Jinolice - Oborský rybník https://www.youtube.com/watch?v=t1NLP0TJwn8
# Tropical Reef Camera powered by EXPLORE.org https://www.youtube.com/watch?v=F109TZt3nRc
# "Shirahama Ohama Beach" 白浜大浜海水浴場（静岡県下田市） https://www.youtube.com/watch?v=xuP8xIbZvmo
# Frenchy’s Clearwater Beach Cam https://www.youtube.com/watch?v=fa7wCF6JL1w
# 「LIVECAMERA」　草津温泉「湯畑」湯滝前  https://www.youtube.com/watch?v=GzbPVzPnT-U
# 「LIVECAMERA 」草津温泉 西の河原・湯川LIVE https://www.youtube.com/watch?v=iPBW7BBoyIw
# 【LIVE CAMERA】飛騨高山ライブカメラ 陣屋前 /Hida-Takayama,In front of the Takayama Jinya https://www.youtube.com/watch?v=PG8kZQ2EkSQ
# 【ライブ配信】丸沼高原スキー場　標高1400m https://www.youtube.com/watch?v=YqXzpB-ardY
# 上高地河童橋ライブカメラ KAMIKOCHI KAPPA-BASHI LIVE CAMERA https://www.youtube.com/watch?v=8bZTa4CBJ2o
# 【LIVE CAMERA】長門湯本温泉ライブカメラ 恩湯（おんとう）前 https://www.youtube.com/watch?v=sgteH34KgM0
# LIVE 道後温泉本館！！冠山カメラ https://www.youtube.com/watch?v=cqjaUAloHzQ
# 【LIVE CAMERA】飛騨高山ライブカメラ 中橋/Hida-Takayama Naka-Bashi Bridge https://www.youtube.com/watch?v=4hx8Xqj0cXM
#
## Play List - my favorite songs
#
# 심수봉 노래 모음 https://www.youtube.com/watch?v=-03cg8u5fdU
# 정태춘, 박은옥 히트곡 모음 듣기ㅣ북한강에서, 촛불 https://www.youtube.com/watch?v=TuukzC2chdo
# 김광석 히트곡 모음 (고음질) https://www.youtube.com/watch?v=yxp2CGK_WWE
# 김현식 베스트 명곡 전부 모음 - 고음질 https://www.youtube.com/watch?v=Speml0pUCB4
# 해바라기 - 노래모음 베스트 20곡 https://www.youtube.com/watch?v=zGsIgF3UBpU
# 자우림 (JAURIM), 김윤아 BEST 40곡 좋은 노래모음 - [연속재생] https://www.youtube.com/watch?v=CYtsEIfpSOg
# 산울림 노래모음 : BEST 15곡 https://www.youtube.com/watch?v=ZBE1McRB5Qg
# This sadness of this darkness https://www.youtube.com/watch?v=9_FSnSQ82T0
# 도시의 그림자(Shadow of City) - 도시의 그림자 (Full Album) https://www.youtube.com/watch?v=LW14PKtNvws
# ♣등려군 노래 모음 11곡♣ https://www.youtube.com/watch?v=tIoLOB1fRgo
#
### MY YOUTUBE URLS END

### TEST END

### MY LOCAL MUSIC - my favorite music directories in my computer.
#
# 아이유 - 꽃갈피 둘/
# 김광석 [2005 Best]/
# fav/
# Camila Cabello/
# moana/
# sia/
#
### MY LOCAL MUSIC END
