#!/bin/bash

### A command line radio player with mpv
#
# Usage: radio [a radio] or radio option [arg ...]
#
# radio fuji
#       - play a fujiyama radio.
#
# radio
#       - play a random radio, press 'q' to play the next.
#         this loops infinitely, press ctrl-c to exit.
#
# radio {-r|--rotate}
#       - rotate a radio in a specific time.
#         this loops infinitely, press ctrl-c to exit.
#
# radio {-a|--all}
#       - display all urls, choose a url number.
#
# radio {-g|--group} {en|kr|jp|mv|lt|ln|lc|pl}
#       - play a group, press 'q' to play the next.
#         this loops randomly and infinitely, press ctrl-c to exit.
#
# radio {-t|--test}
#       - test all radios whether work or not.
#         If failed, it logs the file named report.
#
# radio {-h|--help}
#       - print this help.

### TODO
#
# add more urls
# add local music files

PLAYER="mpv"
PS3="Choose : "
RADIOSTARTLINE="### MY RADIO URLS"
RADIOENDLINE="### MY RADIO URLS END"
YOUTUBESTARTLINE="### MY YOUTUBE URLS"
YOUTUBEENDLINE="### MY YOUTUBE URLS END"
SCRIPTDIR=$(dirname -- "$(readlink -f -- "$0")")
REPORTPATH="$SCRIPTDIR/report"
REPORTFIRSTLINE="### REPORT"
TESTTIME=5
ROTATIONTIME=600
PATTERN="^#\?$\|^##\+\|^#[^ ]"
x=0
while read -r line ; do
    (( x++ ))
    [[ "$line" == "$RADIOSTARTLINE" ]] && break
done < "$0"

# printf "\n RADIOSTARTLINE's number is $x \n"
urllist=$(tail -n +"$(( x + 4 ))" "$0")

x=0
while read -r line ; do
    (( x++ ))
    [[ "$line" == "$RADIOENDLINE" ]] && break
done <<< "$urllist"

radiolist=$(head -n +"$(( x - 2 ))" <<< "$urllist")
# printf "\n radiolist is $radiolist \n"
urlname=$(awk -F 'http' '{print $1}' <<< "$urllist")
# printf "\n urlname is $urlname \n"
radioname=$(awk -F 'http' '{print $1}' <<< "$radiolist")

if [[ -z $1 ]] ; then
    while true ; do
        randomradio=$(shuf -n 1 <<< "$radiolist")
        # PATTERN for comments
        # basic regex: ‘\?’, ‘\+’, ‘\{’, ‘\|’, ‘\(’, and ‘\)’
        (( $(grep -c "$PATTERN" <<< "$randomradio") )) && continue
        printf "\n"
        awk -F 'http' '{print $1}' <<< "$randomradio" | \
            sed 's/# / /' | grep --color=auto .
        printf "\n"
        $PLAYER $(awk -F 'http' '{print FS$2}' <<< "$randomradio") &
        lastbgpid=$!
        wait $lastbgpid
        sleep 1
    done
    exit 0
fi

if [[ $1 =~ ^(-r|--rotate)$ ]] ; then
    while true ; do
        randomradio=$(shuf -n 1 <<< "$radiolist")
        # PATTERN for comments
        (( $(grep -c "$PATTERN" <<< "$randomradio") )) && continue
        printf "\n"
        awk -F 'http' '{print $1}' <<< "$randomradio" | \
            sed 's/# / /' | grep --color=auto .
        printf "\n"
        $PLAYER $(awk -F 'http' '{print FS$2}' <<< "$randomradio") &
        lastbgpid=$!
        sleep $TESTTIME
        # fail playing
        (( ! $(ps -A | grep -c $lastbgpid) )) && continue
        sleep $ROTATIONTIME
        kill -9 $lastbgpid
        sleep 1
    done
    exit 0
fi

[[ $1 =~ ^(-a|--all)$ ]] && radio .

if [[ $1 =~ ^(-g|--group)$ ]] ; then
    x=0
    while read -r line ; do
        (( x++ ))
        case "$2" in
            en) [[ "$line" =~ ^(## English Radio) ]] && break ;;
            kr) [[ "$line" =~ ^(## Korean Radio) ]] && break ;;
            jp) [[ "$line" =~ ^(## Japanese Radio) ]] && break ;;
            mv) [[ "$line" =~ ^(## Music Video) ]] && break ;;
            lt) [[ "$line" =~ ^(## Live Tv) ]] && break ;;
            ln) [[ "$line" =~ ^(## Live News) ]] && break ;;
            lc) [[ "$line" =~ ^(## Live Camera) ]] && break ;;
            pl) [[ "$line" =~ ^(## Play List) ]] && break ;;
            *)printf "\n There is no \"$2\" group."
              printf "\n"
              printf "\n Usage: radio -g {en|kr|jp|mv|lt|ln|lc|pl}"
              printf "\n"
              printf "\n en - English Radio"
              printf "\n kr - Korean Radio"
              printf "\n jp - Japanese Radio"
              printf "\n mv - Music Video"
              printf "\n lt - Live Tv"
              printf "\n ln - Live News"
              printf "\n lc - Live Camera"
              printf "\n pl - Play List"
              printf "\n"
              exit 1
        esac
    done <<< "$urllist"
    grouplist=$(tail -n +"$(( x + 2 ))" <<< "$urllist")
    y=0
    while read -r line ; do
        (( y++ ))
        [[ "$line" =~ ^##+ ]] && break
    done <<< "$grouplist"
    grouplist=$(head -n "$(( y - 2 ))" <<< "$grouplist")
    while true ; do
        randomradio=$(shuf -n 1 <<< "$grouplist")
        (( $(grep -c "$PATTERN" <<< "$randomradio") )) && continue
        printf "\n"
        awk -F 'http' '{print $1}' <<< "$randomradio" | \
            sed 's/# / /' | grep --color=auto .
        printf "\n"
        $PLAYER $(awk -F 'http' '{print FS$2}' <<< "$randomradio") &
        lastbgpid=$!
        wait $lastbgpid
        sleep 1
    done
    exit 0
fi

if [[ $1 =~ ^(-t|--test)$ ]] ; then
    cat > "$REPORTPATH" <<< $REPORTFIRSTLINE
    while read -r line ; do
        printf "\n"
        awk -F 'http' '{print $1}' <<< $line | \
            sed 's/# / /' | grep --color=auto .
        printf "\n"
        $PLAYER $(awk -F 'http' '{print FS$2}' <<< $line)
        lastbgpid=$!
        sleep $TESTTIME
        if (( ! $(ps -A | grep -c $lastbgpid) )) ; then
            echo "Fail: $line" >> "$REPORTPATH"
        else
            kill -9 $lastbgpid
        fi
        sleep 1
    done <<< "$urllist"
    printf "\n"
    cat "$REPORTPATH"
    printf "\n"
    exit 0
fi

if [[ $1 =~ ^(-h|--help)$ ]] ; then
    x=0
    while read -r line ; do
        (( x++ ))
        [[ "$line" =~ ^(# Usage) ]] && break
    done < "$0"
    helplist=$(tail -n +$(( x - 2 )) "$0")
    x=0
    while read -r line ; do
        (( x++ ))
        [[ "$line" =~ (^$) ]] && break
    done <<< "$helplist"
    helplist=$(head -n $x <<< "$helplist")
    printf "\n"
    printf "\n $helplist" | sed 's/#\+//' | sed 's/^ //'
    printf "\n"
    exit 0
fi

# add -F grep option for string
grepcount=$(grep -icF "$1" <<< "$urlname")
# printf "\n grepcount is $grepcount \n"

if (( $grepcount == 1 )) ; then
    printf "\n"
    grep -iF "$1" <<< "$urlname" | sed 's/# / /' | grep --color=auto .
    printf "\n"
    theurlname=$(grep -iF "$1" <<< "$urlname" | sed 's/# / /')
    # printf "\n theurlname is $theurlname \n"
    $PLAYER $(grep -iF "$theurlname" <<< "$urllist" | \
                  awk -F 'http' '{print FS$2}')
elif (( $grepcount > 1 )) ; then
    urlnames=$(grep -iF "$1" <<< "$urlname" | sed 's/^# //' | sed '/^#/d')
    readarray -t arr_urlnames <<< "$urlnames"
    select url in "${arr_urlnames[@]}" ; do
        if [[ $REPLY =~ ^("*"|"0")$ ]] ; then
            printf "\n"
            printf "\n You choose all items."
            printf "\n They'll be played randomly and infinitely."
            printf "\n To exit, press Ctrl-c."
            printf "\n"
            while true ; do
                randomurlname=$(shuf -n 1 <<< "$urlnames")
                printf "\n"
                printf  "\n $randomurlname" | grep --color=auto .
                printf "\n"
                randomurlline=$(grep -iF "$randomurlname" <<< "$urllist")
                $PLAYER $(awk -F 'http' '{print FS$2}' <<< "$randomurlline")
                sleep 1
            done
            exit 0
        fi
        selectedurl="$url"
        break
    done
    printf "\n"
    printf "\n $selectedurl" | grep --color=auto .
    printf "\n"
    $PLAYER $(grep -iF "$selectedurl" <<< "$urllist" | \
                  awk -F 'http' '{print FS$2}')
    exit 0
else
    printf "\n"
    printf "\n Sorry, the \"$1\" does not match."
    printf "\n"
    exit 1
fi

### MY RADIO URLS
#
# write a symptom without any space after # for error log
#
## English Radio
#
# BBC Radio London 94.9 FM http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrldn_mf_p
# NPR 24h Program Stream https://npr-ice.streamguys1.com/live.mp3
# CNN HLN http://tunein.streamguys1.com/cnnhln
# Fox News Radio https://streaming-ent.shoutcast.com/foxnews
# KWSU 1250 Northwest Public Radio NPR News - Pullman, WA http://streams.nwpr.org:8000/NWPRNEWS
# WNPR 90.5 Connecticut Public Radio - Meriden, CT http://16113.live.streamtheworld.com/WNPRFM_SC
# 90.5 WESA Pittsburgh's NPR New Station https://17273.live.streamtheworld.com:443/WESAFM.mp3
#
## Korean Radio
#
# SBS 러브 FM-SBS 라디오 http://slive.ytn.co.kr:1935/live/fmlive_0624_1.sdp/playlist.m3u8
# gukak http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8
# FM 95.1 TBS fm http://58.234.158.60:1935/fmlive/myStream/playlist.m3u8
#
## Japanese Radio
#
# KBS World Japanese Radio http://101.79.244.199:1935/cocotv/_definst_/CH00007/playlist.m3u8
#loading-error Eden of the West http://edenofthewest.com:8080/weeaboo.mp3
# Kishiwada Radio http://61.89.201.27:8000/radikishi.mp3
# Kyoto Living FM (京都リビング FM/きょうと りびんぐ FM) http://musicbird.leanstream.co/JCB104-MP3
# FmHaro!76.1（エフエムハロー!） http://musicbird.leanstream.co/JCB034-MP3
# FM Fujiyama (FMふじやま, JOZZ3CA-FM, 77.6 MHz, Fujikawaguchiko, Yamanashi) http://musicbird.leanstream.co/JCB026-MP3
# Shuunan FM (しゅうなんFM, JOZZ8AJ-FM, 78.4 MHz, Shūnan, Yamaguchi) http://musicbird.leanstream.co/JCB085-MP3
# Air Tesshi (Airてっし, JOZZ1AU-FM, 78.8 MHz, Nayoro, Hokkaido) http://musicbird.leanstream.co/JCB003-MP3
# Umeda FM Be Happy! (ウメダFM Be Happy! 789/エフエムキタ, JOZZ7AK-FM, 78.9MHz, Kita-ku, Osaka) http://musicbird.leanstream.co/JCB068-MP3
# Happy FM Itami (ハッピーエフエムいたみ, JOZZ7AJ-FM, 79.4 MHz, Itami, Hyōgo) http://musicbird.leanstream.co/JCB070-MP3
# FM Yame (FM八女, JOZZ0BY-FM, 80.1 MHz, Yame, Fukuoka) http://musicbird.leanstream.co/JCB086-MP3
# FM Hanako (JOZZ7AA-FM, 82.4 MHz, Moriguchi City, Osaka) http://musicbird.leanstream.co/JCB069-MP3
# Kamakura FM 82.8 (かまくらFM, JOZZ3AF-FM, 82.8 MHz, Kamakura, Kanagawa) http://musicbird.leanstream.co/JCB016-MP3?args=tunein_02
#Ichikawa Urara FM (市川うららFM. JOZZ3AY-FM, 83.0 MHz, Ichikawa, Chiba) http://musicbird.leanstream.co/JCB020-MP3
# Humming FM Takarazuka (ハミングFM宝塚, JOZZ7AT-FM, 83.5 MHz, Takarazuka, Hyōgo) http://musicbird.leanstream.co/JCB071-MP3
# 84.3 FM Edogawa (FMえどがわ, JOZZ3AS-FM, Edogawa City, Tokyo) http://musicbird.leanstream.co/JCB032-MP3
# Shonan Magic Wave (湘南マジックウェィブ, JOZZ3CI-FM, 85.6 MHz, Ōiso, Kanagawa) http://musicbird.leanstream.co/JCB018-MP3
# FM Hana (FMはな, JOZZ1AZ-FM, 87.0 MHz, Nakashibetsu, Hokkaido) http://musicbird.leanstream.co/JCB001-MP3
# Banana FM (バナナエフエム, JOZZ7BE-FM, 87.7 MHz, Wakayama City) http://musicbird.leanstream.co/JCB075-MP3
#
### MY RADIO URLS END



### MY YOUTUBE URLS - You need a youtube-dl to play url.
#
## Music Video
#
# Дария «Нуки» Ставрович «Zombie» - Слепые прослушивания – Голос – Сезон 5 https://www.youtube.com/watch?v=pLN-EnS_QLA
# Дария Ставрович «Круги на воде» - Нокауты - Голос - Сезон 5 https://www.youtube.com/watch?v=AW3EJiRD0ho
# Дария Ставрович «Chandelier» - Полуфинал - Голос - Сезон 5 https://www.youtube.com/watch?v=ltV1yoeIoPM
# Sting - Shape of My Heart (Leon) https://www.youtube.com/watch?v=QK-Z1K67uaA
# What's up - EXCELENTE COVER!!! https://www.youtube.com/watch?v=1NNE0b55AoM
# 나카시마 미카 - 僕が死のうと思ったのは (내가 죽으려고 마음먹었던 것은) https://www.youtube.com/watch?v=C6st9z_iaao
# Sia - Big Girls Cry (Official Video) https://www.youtube.com/watch?v=4NhKWZpkw1Q
# Sia - The Greatest https://www.youtube.com/watch?v=GKSRyLdjsPA
# Sia - Together (from the motion picture Music) https://www.youtube.com/watch?v=vnfGni4_RlI
# Sia - Alive https://www.youtube.com/watch?v=t2NgsJrrAyM
# Sia - Unstoppable https://www.youtube.com/watch?v=H3evCDEXp4I
# Sia - Together (Initial Talk 80s Bootleg Video) https://www.youtube.com/watch?v=4Qi9wP9Smj4
# Sia - Chandelier (Official Music Video) https://www.youtube.com/watch?v=2vjPBrBU-TM
# Sia - Elastic Heart feat. Shia LaBeouf & Maddie Ziegler (Official Video) https://www.youtube.com/watch?v=KWZGAExj-es
# LSD - Thunderclouds (Official Video) ft. Labrinth, Sia, Diplo https://www.youtube.com/watch?v=mILth-K6KvM
# LSD - No New Friends (Official Video) ft. Labrinth, Sia, Diplo https://www.youtube.com/watch?v=kkUIdK9eaIk
# LSD - Audio (Official Video) ft. Sia, Diplo, Labrinth https://www.youtube.com/watch?v=tjA7nAHOAww
#
## Live Tv
#
# 正在直播：CCTV中文国际 https://www.youtube.com/watch?v=vCDDYb_M2B4
# franceinfo - DIRECT TV - actualité france et monde, interviews, documentaires et analyses https://www.youtube.com/watch?v=wwNZKfBLAsc
# Tele1 TV | Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=QTRJR1en1gk
# Adom TV Live https://www.youtube.com/watch?v=T9VZUsOC5M4
# LIVE | Let's go to Broomstown together by watching Robocar POLI TV series! https://www.youtube.com/watch?v=A00EakzkUTc
#
## Live News
#
# LIVE 언제, 어디서나 KBS 24시뉴스 https://www.youtube.com/watch?v=MkQgP7KzjCk
# YTN LIVE 대한민국 24시간 뉴스채널 https://www.youtube.com/watch?v=U_sYIKWhJvk
# [생방송] 연합뉴스TV https://www.youtube.com/watch?v=0GN8t2u3flc
# CNA 24/7 LIVE https://www.youtube.com/watch?v=XWq5kBlakcQ
# ANNnewsCH https://www.youtube.com/watch?v=coYw-eVU0Ks
# Taiwan Formosa live news HD https://www.youtube.com/watch?v=XxJKnDLYZz4
# Taiwan EBC 24h live news https://www.youtube.com/watch?v=RaIJ767Bj_M
# Watch NBC News NOW Live https://www.youtube.com/watch?v=6hRk_zPTN1c
# NBC2 Live Stream https://www.youtube.com/watch?v=tPeUHECNLKs
# Watch The Latest News Headlines and Live Events: ABC News Live https://www.youtube.com/watch?v=w_Ma8oQLmSM
# Al Jazeera English | Live https://www.youtube.com/watch?v=EOBY5J0b9Uo
# Watch Sky News live https://www.youtube.com/watch?v=9Auq9mYxFEE
# Euronews English Live https://www.youtube.com/watch?v=T7mRH8a5pMs
# FRANCE 24 English – LIVE – International Breaking News & Top stories - 24/7 stream https://www.youtube.com/watch?v=FUnJzFT2i84
# Sushant Singh Rajput Death Probe LIVE Updates | LIVE TV 24x7 | Latest News | Republic TV LIVE https://www.youtube.com/watch?v=ckKA-0MUm4E
# LIVE: Puthiya Thalaimurai Live News | Tamil News | Live Tamil News | Ayodhya Ram temple | Sushant https://www.youtube.com/watch?v=fyd-8IcMIJo
# OTV Live 24x7 | Latest News Updates | Coronavirus(COVID-19) News | Unlock 3.0 Updates | Odisha TV https://www.youtube.com/watch?v=AWq8Z8rP7b4
# Sakshi TV LIVE | Today 'Telugu News' LIVE  https://www.youtube.com/watch?v=8McTsOqeueE
# Manorama News LIVE TV https://www.youtube.com/watch?v=jjH6v95z3Nw
# India Today Live TV | Breaking News Live | Latest India News in English https://www.youtube.com/watch?v=dA2cWLqsKBk
# Watch SAMAA TV's News LIVE STREAM 24/7 | Full Pakistan coverage https://www.youtube.com/watch?v=pDXlyQf0Of8
# AajTak Live TV | Ayodhya Ram Mandir | Sushant | Rajasthan | Corona | Breaking News https://www.youtube.com/watch?v=emCd4fr93rs
# LIVE STREAMING KOMPAS TV 24/7 https://www.youtube.com/watch?v=gIB2egm7tL8
# NETTV LIVE 2020 https://www.youtube.com/watch?v=WZ83bBwWZQY
# Channels Television Live https://www.youtube.com/watch?v=-c8LoR84Xjs
# TGRT Haber TV Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=5J8uR3mxq80
# Habertürk TV Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=deKH0pQ7-rg
#
## Live Camera - often off camera
#
# 남산서울타워 파노라마 LIVE https://www.youtube.com/watch?v=am2Ivi346tQ&feature=emb_logo
# 鍛冶町通りライブカメラ［ザザシティ浜松］PTZ（パンチルトズーム）https://www.youtube.com/watch?v=PvoIqPjZFyA&feature=emb_logo
# Shibuya Scramble Crossing Live Camera https://www.youtube.com/watch?v=wUOLcfnUKz0
# 【LIVE CAMERA】渋谷スクランブル交差点 ライブ映像 https://www.youtube.com/watch?v=NnNoL7shdjg
# 【LIVE】Tokyo Shinjuku Live Camera 新宿 大ガード交差点【2020】https://www.youtube.com/watch?v=RQA5RcIZlAM
# Downtown Telluride Live Camera https://www.youtube.com/watch?v=Y_TLxje5Qw4
# LIVE 大阪 道頓堀 ライブカメラ osaka Dotonbori LiveCamera https://www.youtube.com/watch?v=JZ61olPaaSQ
# WATCH NASA: Earth Viewing cameras - Earth From Space ISS feed https://www.youtube.com/watch?v=DDU-rZs-Ic4
# EarthCam Live: Times Square in 4K https://www.youtube.com/watch?v=mRe-514tGMg
# Times Square: 1560 Broadway View Live https://www.youtube.com/watch?v=4qyZLflp-sI
# Times Square: Express View Live https://www.youtube.com/watch?v=uw0lpuMSe9E&feature=emb_logo
# Las Vegas: AE View Live https://www.youtube.com/watch?v=1ZNCtDLUKHw
# Avalanche Bay Indoor Waterpark, Boyne Mountain https://www.youtube.com/watch?v=mm_fnIJ1c6Q&feature=emb_logo
# Jackson Hole Wyoming USA Town Square Live Cam - SeeJH.com https://www.youtube.com/watch?v=1EiC9bvVGnk https://www.youtube.com/watch?v=j_-4HMuw7PY
# White Mountains TV Live Cam: North Conway Village
# Webcam Lanzarote - Live Stream from the Beachbar in Costa Teguise https://www.youtube.com/watch?v=D-N5ZiWzAC0&feature=emb_logo
# Live Stream — Public Square, Watertown NY — Jake Johnson Properties https://www.youtube.com/watch?v=qP1y7Tdab7Y&feature=emb_logo
# LIVE · Thailand / Koh Phangan / Haad Rin · Full Moon Party beach (AI Camera looking for people) https://www.youtube.com/watch?v=-Fen7JP8oHI&feature=emb_logo
# LIVE · Thailand / Koh Phangan · Thong Sala center (Mandolino Pizzeria) https://www.youtube.com/watch?v=1nnt_Beuo88&feature=emb_logo
# Lamai Walking Street Live Stream From Lamai, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=17Deeq8N2e4
# Sweet Soul Cafe Cam 2, Soi Green Mango, Chaweng, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=C1LlLCsWdcg
# Sweet Soul Cafe Cam 1, Soi Green Mango, Chaweng, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=B_2He_msuWU
# Hush Bar Cam, Soi Green Mango, Chaweng, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=wqvStiZyVBI
# Crystal Bay Yacht Club Live Stream From Lamai, Koh Samui, Thailand | Live HD Webcam | SamuiWebcam https://www.youtube.com/watch?v=aJdwAUUbFL8
# LIVE · Thailand / Koh Phangan / Haad Rin · Full Moon Party beach (Seaview Sunrise Resort) https://www.youtube.com/watch?v=9WbCh2AE_NU
# Banff, AB Canada Live Cam https://www.youtube.com/watch?v=Tpchwvyv6yU
# Grancanaria.live | Playa del Inglés - Yumbo Center - LIVE ultraHD 4K PTZ https://www.youtube.com/watch?v=cvYNX6OONW4&feature=emb_logo
# WebCam.NL | www.sportsatsea.nl - live HD PTZ camera. https://www.youtube.com/watch?v=5rkyZrQv674&feature=emb_logo
# Beach Bar live HD Webcam in Cruz Bay https://www.youtube.com/watch?v=GrZ8LL8yAqs&feature=emb_logo
# The central beach of Lignano Sabbiadoro (Italy) - Spiaggia LIVE streaming HD Webcam https://www.youtube.com/watch?v=2Xjog3Xs-P0
# LIVE Deerfield Beach - Beach Camera https://www.youtube.com/watch?v=-HAi_5IIAYg&feature=emb_logo
# Dania Beach Pier and Beach Cam https://www.youtube.com/watch?v=bEoNVd3spEM&feature=emb_logo
# Sportovní areál - Maškova zahrada, Turnov https://www.youtube.com/watch?v=meUtwDS6fVk&feature=emb_logo
#
## Play List
#
# 심수봉 노래모음: best 18곡 연속듣기 https://www.youtube.com/watch?v=2WPMh5faFpw
#
### MY YOUTUBE URLS END
