#!/bin/bash

### simple mpv radio
#
# $ radio fuji
#
# for all radio urls -> $ radio .

## TODO:
# fail -1 or succeed +1, delete radio_url at hitting -10 point
# score=0

input="$1"
PLAYER="mpv"
PS3="Choose : "
x=0
STARTLINE="### radio_urls"

while read -r line ; do
    (( x++ ))
    if [[ "$line" == "$STARTLINE" ]]; then
        break
    fi
done < "$0"

radiolist=$(tail -n +"$(( x + 2 ))" "$0")
radioname=$(awk -F http '{print $1}' <<< "$radiolist")
radiourl=$(awk -F http '{print FS$2}' <<< "$radiolist")
grepcount=$(grep -ic "^# .*\b$input" <<< "$radioname")

if (( $grepcount == 1 )) ; then
    printf "\n"
    grep -i "^# .*\b$input" <<< "$radioname" | sed 's/# / /'
    printf "\n"
    theradioname=$(grep -i "^# .*\b$input" <<< "$radioname" | sed 's/# / /')
    $PLAYER $(grep -i "$theradioname" <<< "$radiolist" | \
                  awk -F http '{print FS$2}')
elif (( $grepcount > 1 )) ; then
    radionames=$(grep -i "^# .*\b$input" <<< "$radioname" | sed 's/# //')
    readarray -t arr_radionames <<< "$radionames"
    select radio in "${arr_radionames[@]}" ; do
        selectedradio="$radio"
        break
    done
    printf "\n $selectedradio\n\n"
    $PLAYER $(grep -i "$selectedradio" <<< "$radiolist" | \
                  awk -F http '{print FS$2}')
else
    printf "\nNo match radio url.\n"
fi



### radio_urls
#
# Eden of the West http://edenofthewest.com:8080/weeaboo.mp3
# Kishiwada Radio http://61.89.201.27:8000/radikishi.mp3
# Kyoto Living FM (京都リビング FM/きょうと りびんぐ FM) http://musicbird.leanstream.co/JCB104-MP3
# FmHaro!76.1（エフエムハロー!） http://musicbird.leanstream.co/JCB034-MP3
# FM Fujiyama (FMふじやま, JOZZ3CA-FM, 77.6 MHz, Fujikawaguchiko, Yamanashi) http://musicbird.leanstream.co/JCB026-MP3
# Shuunan FM (しゅうなんFM, JOZZ8AJ-FM, 78.4 MHz, Shūnan, Yamaguchi) http://musicbird.leanstream.co/JCB085-MP3
# Air Tesshi (Airてっし, JOZZ1AU-FM, 78.8 MHz, Nayoro, Hokkaido) http://musicbird.leanstream.co/JCB003-MP3
# Umeda FM Be Happy! (ウメダFM Be Happy! 789/エフエムキタ, JOZZ7AK-FM, 78.9MHz, Kita-ku, Osaka) http://musicbird.leanstream.co/JCB068-MP3
# Happy FM Itami (ハッピーエフエムいたみ, JOZZ7AJ-FM, 79.4 MHz, Itami, Hyōgo) http://musicbird.leanstream.co/JCB070-MP3
# FM Yame (FM八女, JOZZ0BY-FM, 80.1 MHz, Yame, Fukuoka) http://musicbird.leanstream.co/JCB086-MP3
# FM Hanako (JOZZ7AA-FM, 82.4 MHz, Moriguchi City, Osaka) http://musicbird.leanstream.co/JCB069-MP3
# Kamakura FM 82.8 (かまくらFM, JOZZ3AF-FM, 82.8 MHz, Kamakura, Kanagawa) http://musicbird.leanstream.co/JCB016-MP3?args=tunein_02
# Ichikawa Urara FM (市川うららFM. JOZZ3AY-FM, 83.0 MHz, Ichikawa, Chiba) http://musicbird.leanstream.co/JCB020-MP3
# Humming FM Takarazuka (ハミングFM宝塚, JOZZ7AT-FM, 83.5 MHz, Takarazuka, Hyōgo) http://musicbird.leanstream.co/JCB071-MP3
# 84.3 FM Edogawa (FMえどがわ, JOZZ3AS-FM, Edogawa City, Tokyo) http://musicbird.leanstream.co/JCB032-MP3
# Shonan Magic Wave (湘南マジックウェィブ, JOZZ3CI-FM, 85.6 MHz, Ōiso, Kanagawa) http://musicbird.leanstream.co/JCB018-MP3
# FM Hana (FMはな, JOZZ1AZ-FM, 87.0 MHz, Nakashibetsu, Hokkaido) http://musicbird.leanstream.co/JCB001-MP3
# Banana FM (バナナエフエム, JOZZ7BE-FM, 87.7 MHz, Wakayama City) http://musicbird.leanstream.co/JCB075-MP3
# SBS 러브 FM-SBS 라디오 http://slive.ytn.co.kr:1935/live/fmlive_0624_1.sdp/playlist.m3u8
# gukak http://mgugaklive.nowcdn.co.kr/gugakradio/gugakradio.stream/playlist.m3u8
# FM 95.1 TBS fm http://58.234.158.60:1935/fmlive/myStream/playlist.m3u8
# KBS World Japanese Radio http://101.79.244.199:1935/cocotv/_definst_/CH00007/playlist.m3u8
# NPR 24h Program Stream https://npr-ice.streamguys1.com/live.mp3
# CNN HLN http://tunein.streamguys1.com/cnnhln
# Fox News Radio https://streaming-ent.shoutcast.com/foxnews
# KWSU 1250 Northwest Public Radio NPR News - Pullman, WA http://streams.nwpr.org:8000/NWPRNEWS
# WNPR 90.5 Connecticut Public Radio - Meriden, CT http://16113.live.streamtheworld.com/WNPRFM_SC
# 90.5 WESA Pittsburgh's NPR New Station https://17273.live.streamtheworld.com:443/WESAFM.mp3
# BBC Radio London 94.9 FM http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrldn_mf_p
