#!/bin/bash

# BBC Radio London 94.9 FM http://bbcmedia.ic.llnwd.net/stream/bbcmedia_lrldn_mf_p
# NPR 24h Program Stream https://npr-ice.streamguys1.com/live.mp3
# CNN HLN http://tunein.streamguys1.com/cnnhln
# Fox News Radio https://streaming-ent.shoutcast.com/foxnews
# KWSU 1250 Northwest Public Radio NPR News - Pullman, WA http://streams.nwpr.org:8000/NWPRNEWS
# WNPR 90.5 Connecticut Public Radio - Meriden, CT http://16113.live.streamtheworld.com/WNPRFM_SC
# 90.5 WESA Pittsburgh's NPR New Station https://17273.live.streamtheworld.com:443/WESAFM.mp3
