#!/bin/bash

# 正在直播：CCTV中文国际 https://www.youtube.com/watch?v=vCDDYb_M2B4
# franceinfo - DIRECT TV - actualité france et monde, interviews, documentaires et analyses https://www.youtube.c
# Tele1 TV | Canlı Yayın ᴴᴰ https://www.youtube.com/watch?v=TDy-nmXZNQM
# Adom TV Live https://www.youtube.com/watch?v=LIb1ADo0pGs
